### ISSUE TITLE
Can't resolve 'd3-selection' in '...\node_modules\geostyler-legend\dist\LegendRenderer'

### ISSUE THREAD

**Issue by fbeqirllari** [camptocamp/inkmap#51] opened 2022-08-27 18:09 UTC
C:\Users\user\Downloads\inkmap>npm run demo

> @camptocamp/inkmap@1.2.0 demo C:\Users\user\Downloads\inkmap
> webpack-dev-server --config demo/webpack.config.js

i ｢wds｣: Project is running at http://localhost:8081/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\user\Downloads\inkmap\demo
× ｢wdm｣: Hash: db444d23ff938e1a70ae
Version: webpack 4.46.0
Time: 9951ms
Built at: 24/08/2022 16:45:14
               Asset      Size         Chunks                   Chunk Names
                0.js   814 KiB              0  [emitted]
            0.js.map   687 KiB              0  [emitted] [dev]
                1.js    46 KiB              1  [emitted]
            1.js.map  53.1 KiB              1  [emitted] [dev]
                2.js   375 KiB              2  [emitted]
            2.js.map   428 KiB              2  [emitted] [dev]
              app.js  4.68 MiB            app  [emitted]        app
          app.js.map  4.76 MiB            app  [emitted] [dev]  app
          index.html  25.5 KiB                 [emitted]
    inkmap-worker.js  3.95 MiB  inkmap-worker  [emitted]        inkmap-worker
inkmap-worker.js.map  3.89 MiB  inkmap-worker  [emitted] [dev]  inkmap-worker
Entrypoint app = app.js app.js.map
Entrypoint inkmap-worker = inkmap-worker.js inkmap-worker.js.map
[0] multi (webpack)-dev-server/client?http://localhost:8081 ./demo/index.js 40 bytes {app} [built]
[1] multi (webpack)-dev-server/client?http://localhost:8081 ./src/worker/index.js 40 bytes {inkmap-worker} [built]
[./demo/elements/custom-button.js] 1.4 KiB {app} [built]
[./demo/elements/custom-progress.js] 3.3 KiB {app} [built]
[./demo/elements/print-spec.js] 4.52 KiB {app} [built]
[./demo/elements/progress-bars.js] 728 bytes {app} [built]
[./demo/examples/01-simple.js] 603 bytes {app} [built]
[./demo/examples/02-progress.js] 1 KiB {app} [built]
[./demo/examples/03-cancel.js] 1.3 KiB {app} [built]
[./demo/examples/04-jobs.js] 1010 bytes {app} [built]
[./demo/examples/05-pdf.js] 2.27 KiB {app} [built]
[./demo/examples/06-projection.js] 897 bytes {app} [built]
[./demo/index.js] 419 bytes {app} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8081] (webpack)-dev-server/client?http://localhost:8081 4.29 KiB {app} {inkmap-worker} [built]
[./src/worker/index.js] 302 bytes {inkmap-worker} [built]
    + 1196 hidden modules

ERROR in ./node_modules/geostyler-legend/dist/LegendRenderer/LegendRenderer.js
Module not found: Error: Can't resolve 'd3-selection' in 'C:\Users\user\Downloads\inkmap\node_modules\geostyler-legend\dist\LegendRenderer'
 @ ./node_modules/geostyler-legend/dist/LegendRenderer/LegendRenderer.js 42:21-44
 @ ./src/shared/widgets/legends.js
 @ ./src/main/index.js
 @ ./demo/examples/01-simple.js
 @ ./demo/index.js
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./demo/index.html] 15.8 KiB {HtmlWebpackPlugin_0} [built]
i ｢wdm｣: Failed to compile.
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'

npm WARN geostyler-legend@2.2.0 requires a peer of d3@^6.7.0 but none is installed. You must install peer dependencies yourself.

**Comment by jahow** [comment] 2022-08-28 12:24
I cannot reproduce with the latest node LTS. Can you please give your version of node/npm?

**Comment by fbeqirllari** [comment] 2022-08-28 15:16
node v14.15.3
npm 6.14.9

**Comment by jahow** [comment] 2022-08-29 07:49
I think we can just specify node 16 as a required version; otherwise it feels wrong to add d3 as a direct dependency of the library. What do you think?

**Comment by fbeqirllari** [comment] 2022-09-03 11:56
@jahow i think this is the best option.

**Comment by fbeqirllari** [comment] 2022-09-03 11:57
@jahow when so you plan to upload the latest changes on npm?

**Comment by jahow** [comment] 2022-09-03 12:23
I'll do a version 1.2.1 with this change and your contribution right now if that's ok!

**Comment by fbeqirllari** [comment] 2022-09-03 12:34
Yes thank you!

**Comment by jahow** [comment] 2022-09-03 12:44
Fixed in v1.3.0!

**Closed** 2022-09-03 12:45 UTC
